import type { PrinterTelemetry } from "../../agent/src/protocol";
import type { Printer, ProductionJob } from "@/types/db";

export const NOW = new Date("2026-09-26T12:00:00Z");
export const iso = (secondsAgo: number) => new Date(NOW.getTime() - secondsAgo * 1000).toISOString();

export function telemetry(over: Partial<PrinterTelemetry> = {}): PrinterTelemetry {
  return {
    status: "ready",
    name: "AD5X",
    pid: 38,
    firmwareVersion: "1.1.7",
    macAddress: null,
    ipAddress: "192.168.1.50",
    nozzleCount: 1,
    nozzleModel: "0.4",
    camera: 2,
    cameraStreamUrl: null,
    jobId: null,
    printFileName: null,
    printProgress: 0,
    printLayer: 0,
    targetPrintLayer: 0,
    printDuration: 0,
    estimatedTime: 0,
    nozzleTemp: 25,
    nozzleTargetTemp: 0,
    bedTemp: 24,
    bedTargetTemp: 0,
    chamberTemp: null,
    chamberTargetTemp: null,
    rightFilamentType: "PLA",
    leftFilamentType: null,
    hasRightFilament: true,
    hasLeftFilament: null,
    estimatedRightWeight: null,
    estimatedLeftWeight: null,
    hasMaterialStation: false,
    materialStation: null,
    directFeed: { material: "PLA", colour: "#FFFFFF", stateAction: 0 },
    doorStatus: null,
    lightStatus: null,
    remainingDiskSpaceGb: null,
    cumulativePrintMinutes: null,
    cumulativeFilamentMm: null,
    errorCode: null,
    ...over,
  };
}

export function printer(over: Partial<Printer> = {}): Printer {
  return {
    id: "p1",
    organization_id: "o1",
    name: "AD5X",
    manufacturer: "Flashforge",
    model: "AD5X",
    status: "idle",
    status_source: "integration",
    status_updated_at: iso(600),
    ip_address: "192.168.1.50",
    location: null,
    capabilities: [],
    build_volume: null,
    notes: null,
    integration_provider: null,
    integration_device_id: null,
    serial_number: "SNAD5X0001",
    connection_mode: "agent_lan",
    agent_id: "a1",
    lan_port: 8899,
    firmware_version: "1.1.7",
    connection_state: "connected",
    consecutive_failures: 0,
    last_seen_at: iso(5),
    last_heartbeat_at: iso(5),
    latency_ms: 40,
    last_error: null,
    last_error_at: null,
    telemetry: telemetry(),
    telemetry_at: iso(5),
    telemetry_source: "flashforge_lan",
    raw_status: "ready",
    current_external_job_id: null,
    current_job_id: null,
    multi_colour: true,
    colour_channels: 4,
    camera: "unknown",
    live_checklist: {},
    live_verified_at: iso(86400),
    live_verified_by: null,
    bed_clear: true,
    bed_clear_confirmed_at: null,
    is_demo: false,
    archived_at: null,
    created_at: iso(999999),
    updated_at: iso(5),
    ...over,
  };
}

export function job(over: Partial<ProductionJob> = {}): ProductionJob {
  return {
    id: "j1",
    job_number: 42,
    organization_id: "o1",
    order_id: "ord1",
    order_item_id: null,
    product_id: "prod1",
    variant_id: null,
    product_name: "Dragon",
    quantity: 1,
    printer_id: "p1",
    status: "queued",
    priority: "normal",
    queue_position: 1,
    material: "PLA",
    colour: "#FFFFFF",
    estimated_minutes: 60,
    actual_minutes: null,
    estimated_grams: 20,
    actual_grams: null,
    filament_id: null,
    accumulated_minutes: 0,
    last_resumed_at: null,
    started_at: null,
    completed_at: null,
    failed_at: null,
    failure_reason: null,
    attempts: 1,
    notes: null,
    external_job_ref: null,
    print_file_id: "f1",
    external_printer_job_id: null,
    printer_file_name: "PF-JOB-0042-Dragon.gcode",
    printer_status: null,
    progress: null,
    remaining_seconds: null,
    printer_elapsed_seconds: null,
    current_layer: null,
    total_layers: null,
    last_telemetry_at: null,
    sent_at: null,
    multi_colour: false,
    colour_channels: 1,
    ifs_required: false,
    filament_assignments: [],
    needs_attention: false,
    attention_code: null,
    attention_reason: null,
    auto_dispatched: false,
    filament_recorded: false,
    is_demo: false,
    created_at: iso(3600),
    updated_at: iso(60),
    ...over,
  };
}
