import { deflateRawSync, inflateRawSync } from "node:zlib";
import { describe, expect, it } from "vitest";
import {
  classifyFileName,
  listZipEntries,
  parseDuration,
  parseGcodeMetadata,
  parseSliceInfo,
  sliced3mfGcodeEntries,
  zipEntryData,
} from "@/lib/printers/slicer-metadata";

/** Minimal ZIP writer for tests (stored or deflated entries). */
function zip(entries: { name: string; data: string; deflate?: boolean }[]) {
  const parts: Buffer[] = [];
  const central: Buffer[] = [];
  let offset = 0;
  for (const e of entries) {
    const raw = Buffer.from(e.data);
    const body = e.deflate ? deflateRawSync(raw) : raw;
    const name = Buffer.from(e.name);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(e.deflate ? 8 : 0, 8);
    local.writeUInt32LE(body.length, 18);
    local.writeUInt32LE(raw.length, 22);
    local.writeUInt16LE(name.length, 26);
    const cen = Buffer.alloc(46);
    cen.writeUInt32LE(0x02014b50, 0);
    cen.writeUInt16LE(e.deflate ? 8 : 0, 10);
    cen.writeUInt32LE(body.length, 20);
    cen.writeUInt32LE(raw.length, 24);
    cen.writeUInt16LE(name.length, 28);
    cen.writeUInt32LE(offset, 42);
    parts.push(local, name, body);
    central.push(cen, name);
    offset += 30 + name.length + body.length;
  }
  const cd = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(cd.length, 12);
  end.writeUInt32LE(offset, 16);
  return new Uint8Array(Buffer.concat([...parts, cd, end]));
}

describe("file types", () => {
  it("accepts sliced formats and rejects models that still need slicing", () => {
    expect(classifyFileName("part.gcode")).toEqual({ type: "gcode" });
    expect(classifyFileName("part.GX")).toEqual({ type: "gx" });
    expect(classifyFileName("part.gcode.3mf")).toEqual({ type: "3mf" });
    expect(classifyFileName("part.stl")).toMatchObject({ error: expect.stringMatching(/Slice it/) });
    expect(classifyFileName("part.step")).toHaveProperty("error");
    expect(classifyFileName("notes.txt")).toHaveProperty("error");
  });
});

describe("G-code metadata", () => {
  it("parses durations", () => {
    expect(parseDuration("1h 2m 3s")).toBe(3723);
    expect(parseDuration("1d 0h 5m")).toBe(86700);
    expect(parseDuration("n/a")).toBeNull();
  });
  it("reads Orca-style header/footer comments", () => {
    const g = [
      "; HEADER_BLOCK_START",
      "; generated by OrcaSlicer 2.2.0 on 2026-09-20 at 10:00:00",
      "; total layer number: 150",
      "; HEADER_BLOCK_END",
      "G28",
      "; filament used [g] = 12.34, 3.21",
      "; estimated printing time (normal mode) = 1h 2m 3s",
      "; filament_type = PLA;PETG",
      "; filament_colour = #FFFFFF;#000000",
      "; printer_model = Flashforge AD5X",
      "; printer_settings_id = Flashforge AD5X 0.4 Nozzle",
      "; nozzle_diameter = 0.4",
    ].join("\n");
    const m = parseGcodeMetadata(g);
    expect(m).toMatchObject({
      slicer: "OrcaSlicer",
      slicerVersion: "2.2.0",
      printerModel: "Flashforge AD5X",
      printerProfile: "Flashforge AD5X 0.4 Nozzle",
      estimatedSeconds: 3723,
      filamentGrams: 15.55,
      nozzleDiameter: 0.4,
      layers: 150,
    });
    expect(m.filaments).toEqual([
      { channel: 1, material: "PLA", colour: "#FFFFFF", grams: 12.34 },
      { channel: 2, material: "PETG", colour: "#000000", grams: 3.21 },
    ]);
  });
  it("returns nulls rather than guesses when nothing is there", () => {
    const m = parseGcodeMetadata("G28\nG1 X0 Y0\n");
    expect(m).toMatchObject({ slicer: null, estimatedSeconds: null, filamentGrams: null, printerModel: null });
    expect(m.filaments).toEqual([]);
  });
});

describe("3MF", () => {
  const sliceInfo = `<?xml version="1.0"?><config><plate><metadata key="index" value="1"/><metadata key="prediction" value="3723"/><metadata key="weight" value="15.55"/>
    <filament id="1" type="PLA" color="#FFFFFF" used_m="4.1" used_g="12.34"/><filament id="2" type="PLA" color="#FF0000" used_m="1" used_g="3.21"/></plate></config>`;

  it("finds the sliced plate G-code and reads slice_info (deflated)", () => {
    const buf = zip([
      { name: "3D/3dmodel.model", data: "<model/>", deflate: true },
      { name: "Metadata/plate_1.gcode", data: "G28\n", deflate: true },
      { name: "Metadata/slice_info.config", data: sliceInfo, deflate: true },
    ]);
    const entries = listZipEntries(buf);
    expect(entries.map((e) => e.name)).toContain("Metadata/slice_info.config");
    expect(sliced3mfGcodeEntries(entries)).toHaveLength(1);
    const e = entries.find((x) => x.name === "Metadata/slice_info.config")!;
    const xml = inflateRawSync(zipEntryData(buf, e)).toString();
    expect(parseSliceInfo(xml)).toMatchObject({
      estimatedSeconds: 3723,
      filamentGrams: 15.55,
      filaments: [
        { channel: 1, material: "PLA", colour: "#FFFFFF", grams: 12.34 },
        { channel: 2, material: "PLA", colour: "#FF0000", grams: 3.21 },
      ],
    });
  });
  it("detects an unsliced project 3MF", () => {
    const entries = listZipEntries(zip([{ name: "3D/3dmodel.model", data: "<model/>" }]));
    expect(sliced3mfGcodeEntries(entries)).toHaveLength(0);
  });
  it("rejects non-ZIP data", () => {
    expect(() => listZipEntries(new TextEncoder().encode("not a zip at all, sorry".repeat(3)))).toThrow(/Not a valid 3MF/);
  });
});
