import type { FilamentAssignment, PrintFileType } from "@/types/db";

/**
 * Reads what a slicer wrote into a sliced file, so the upload form can be
 * pre-filled. PrintFlow does not slice anything: files must already be
 * sliced for a specific printer. Every value is optional and editable.
 */

export interface SlicerMetadata {
  slicer: string | null;
  slicerVersion: string | null;
  printerModel: string | null;
  printerProfile: string | null;
  estimatedSeconds: number | null;
  filamentGrams: number | null;
  nozzleDiameter: number | null;
  layers: number | null;
  filaments: FilamentAssignment[];
}

const UNSLICED = new Set(["stl", "obj", "step", "stp", "amf", "ply", "f3d", "blend", "scad"]);

export function classifyFileName(name: string): { type: PrintFileType } | { error: string } {
  const ext = name.toLowerCase().split(".").pop() ?? "";
  if (ext === "gcode" || ext === "g") return { type: "gcode" };
  if (ext === "gx") return { type: "gx" };
  if (ext === "3mf") return { type: "3mf" };
  if (UNSLICED.has(ext)) {
    return { error: `.${ext} is a 3D model, not a print file. Slice it for the printer first (e.g. in Orca-Flashforge) and upload the result.` };
  }
  return { error: "Upload a sliced print file (.gcode, .gx or a sliced .3mf)." };
}

/** "1d 2h 3m 4s", "2h 5m", "45m 10s" → seconds */
export function parseDuration(text: string): number | null {
  const re = /(\d+(?:\.\d+)?)\s*([dhms])/gi;
  let total = 0;
  let found = false;
  for (const m of text.matchAll(re)) {
    found = true;
    const n = Number(m[1]);
    total += n * { d: 86400, h: 3600, m: 60, s: 1 }[m[2].toLowerCase() as "d" | "h" | "m" | "s"];
  }
  return found ? Math.round(total) : null;
}

function firstNumber(s: string | undefined) {
  if (!s) return null;
  const m = s.match(/-?\d+(?:\.\d+)?/);
  return m ? Number(m[0]) : null;
}

function sumNumbers(s: string | undefined) {
  if (!s) return null;
  const nums = [...s.matchAll(/\d+(?:\.\d+)?/g)].map((m) => Number(m[0]));
  return nums.length ? Math.round(nums.reduce((a, b) => a + b, 0) * 100) / 100 : null;
}

const splitList = (s: string | undefined) =>
  (s ?? "")
    .split(/[;,]/)
    .map((x) => x.trim().replace(/^"|"$/g, ""))
    .filter(Boolean);

/** Parses the comment header/footer of G-code (Orca/Bambu/Prusa-style and FlashPrint-style keys). */
export function parseGcodeMetadata(text: string): SlicerMetadata {
  const kv = new Map<string, string>();
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line.startsWith(";")) continue;
    const body = line.replace(/^;+\s*/, "");
    const m = body.match(/^([^=:]+?)\s*[=:]\s*(.+)$/);
    if (m) {
      const key = m[1].trim().toLowerCase();
      if (!kv.has(key)) kv.set(key, m[2].trim());
    }
  }
  const generated = text.match(/;\s*generated by\s+([A-Za-z][\w\- ]*?)\s+v?(\d[\w.\-+]*)/i);
  const flashprint = kv.get("generated by")?.match(/^(\S+)\s*(\S+)?/);

  let seconds: number | null = null;
  for (const key of ["estimated printing time (normal mode)", "estimated printing time", "total estimated time", "estimated_time(s)", "print time", "time"]) {
    const v = kv.get(key);
    if (!v) continue;
    seconds = /^\d+(\.\d+)?$/.test(v) ? Math.round(Number(v)) : parseDuration(v);
    if (seconds) break;
  }
  const modelTime = text.match(/total estimated time:\s*([^;\n]+)/i);
  if (!seconds && modelTime) seconds = parseDuration(modelTime[1]);

  const grams = sumNumbers(kv.get("total filament weight [g]") ?? kv.get("filament used [g]") ?? kv.get("filament_used_g"));
  const types = splitList(kv.get("filament_type"));
  const colours = splitList(kv.get("filament_colour") ?? kv.get("extruder_colour"));
  const perGrams = (kv.get("filament used [g]") ?? "").split(",").map((x) => firstNumber(x));
  const count = Math.max(types.length, colours.length);
  const filaments: FilamentAssignment[] = [];
  for (let i = 0; i < count; i++) {
    filaments.push({ channel: i + 1, material: types[i] ?? types[0] ?? null, colour: colours[i] ?? null, grams: perGrams[i] ?? null });
  }

  return {
    slicer: generated?.[1]?.trim() ?? flashprint?.[1] ?? null,
    slicerVersion: generated?.[2] ?? flashprint?.[2] ?? null,
    printerModel: kv.get("printer_model") ?? kv.get("machine_type") ?? kv.get("machine type") ?? null,
    printerProfile: kv.get("printer_settings_id") ?? kv.get("printer_preset") ?? null,
    estimatedSeconds: seconds,
    filamentGrams: grams,
    nozzleDiameter: firstNumber(kv.get("nozzle_diameter")),
    layers: firstNumber(kv.get("total layer number") ?? kv.get("total layers count") ?? kv.get("layer_count")),
    filaments,
  };
}

/** Parses Metadata/slice_info.config from a sliced 3MF (Orca/Bambu format). */
export function parseSliceInfo(xml: string): Partial<SlicerMetadata> {
  const meta = (key: string) => xml.match(new RegExp(`<metadata\\s+key="${key}"\\s+value="([^"]*)"`, "i"))?.[1];
  const filaments: FilamentAssignment[] = [];
  for (const m of xml.matchAll(/<filament\s+([^>]*?)\/?>/gi)) {
    const attr = (name: string) => m[1].match(new RegExp(`${name}="([^"]*)"`))?.[1];
    const id = Number(attr("id"));
    if (!Number.isFinite(id)) continue;
    filaments.push({ channel: id, material: attr("type") ?? null, colour: attr("color") ?? null, grams: firstNumber(attr("used_g")) });
  }
  return {
    estimatedSeconds: firstNumber(meta("prediction")),
    filamentGrams: firstNumber(meta("weight")),
    printerModel: meta("printer_model_id") ?? null,
    nozzleDiameter: firstNumber(meta("nozzle_diameters")),
    filaments: filaments.sort((a, b) => a.channel - b.channel),
  };
}

// ---------------------------------------------------------------------------
// Minimal ZIP directory reader (3MF files are ZIP archives)
// ---------------------------------------------------------------------------

export interface ZipEntry {
  name: string;
  method: number;
  compressedSize: number;
  size: number;
  localHeaderOffset: number;
}

/** Lists entries from a ZIP's central directory. Throws if the data is not a ZIP. */
export function listZipEntries(buf: Uint8Array): ZipEntry[] {
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  let eocd = -1;
  for (let i = buf.length - 22; i >= Math.max(0, buf.length - 65557); i--) {
    if (view.getUint32(i, true) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error("Not a valid 3MF (ZIP) file.");
  const count = view.getUint16(eocd + 10, true);
  let off = view.getUint32(eocd + 16, true);
  const entries: ZipEntry[] = [];
  const dec = new TextDecoder();
  for (let i = 0; i < count; i++) {
    if (off + 46 > buf.length || view.getUint32(off, true) !== 0x02014b50) throw new Error("Corrupt 3MF (ZIP) directory.");
    const method = view.getUint16(off + 10, true);
    const compressedSize = view.getUint32(off + 20, true);
    const size = view.getUint32(off + 24, true);
    const nameLen = view.getUint16(off + 28, true);
    const extraLen = view.getUint16(off + 30, true);
    const commentLen = view.getUint16(off + 32, true);
    const localHeaderOffset = view.getUint32(off + 42, true);
    const name = dec.decode(buf.subarray(off + 46, off + 46 + nameLen));
    entries.push({ name, method, compressedSize, size, localHeaderOffset });
    off += 46 + nameLen + extraLen + commentLen;
  }
  return entries;
}

/** The raw (possibly deflated) bytes of an entry. */
export function zipEntryData(buf: Uint8Array, e: ZipEntry): Uint8Array {
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  const off = e.localHeaderOffset;
  if (view.getUint32(off, true) !== 0x04034b50) throw new Error("Corrupt 3MF (ZIP) entry.");
  const start = off + 30 + view.getUint16(off + 26, true) + view.getUint16(off + 28, true);
  return buf.subarray(start, start + e.compressedSize);
}

/** A 3MF is only printable if the slicer embedded G-code for a plate. */
export function sliced3mfGcodeEntries(entries: ZipEntry[]) {
  return entries.filter((e) => /^Metadata\/plate_\d+\.gcode$/i.test(e.name));
}
